spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
  thymeleaf:
    cache: false
  mail:
    host: smtp.naver.com
    port: 465
    username: Email@naver.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace
    org.springframework.security: DEBUG

server:
  error:
    whitelabel:
      enabled: false
