spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
  thymeleaf:
    cache: false
  mail:
    host: smtp.naver.com
    port: 465
    username: Email@naver.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: Fu27TG3yPMTeZterX42W
            client-secret: XjDfC6fEy6
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-name: Naver
            scope: name, email

          kakao:
            client-id: 67a457e9b8752d60a2f628ebc9e4575a
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

server:
  error:
    whitelabel:
      enabled: false


