spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ecoswapshop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace
    org.springframework.security: DEBUG

server:
  error:
    whitelabel:
      enabled=false:
