name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin' # Eclipse Temurin은 AdoptOpenJDK의 계승 프로젝트입니다.

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Deploy to AWS Elastic Beanstalk
        if: github.ref == 'refs/heads/main'
        uses: einaregilsson/beanstalk-deploy@v13
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}   # github Repository secrets
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # github Repository secrets
          application_name: 'your-application-name' # AWS Elastic Beanstalk에 있는 애플리케이션의 이름.
          environment_name: 'your-environment-name' # 배포할 환경의 이름.
          region: 'us-west-2'
          version_label: ${{ github.sha }} # 커밋 SHA
          deployment_package: 'Ecoswapshop.zip' # 배포할 압축된 파일의 경로.
